import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { cn } from '@/lib/utils'
import { AuthWrapper } from '@/components/layouts'
import TanstackProvider from '@/providers/tanstack'
import { Toaster } from 'sonner'
import { CheckCircle, WarningCircle, Info } from '@phosphor-icons/react/dist/ssr'

const berkeley = localFont({
	src: './fonts/Berkeley.otf',
	variable: '--font-berkeley',
})

const cerealLight = localFont({
	src: './fonts/AirbnbCereal_W_Lt.otf',
	variable: '--font-lausanne-light',
})

const cerealRegular = localFont({
	src: './fonts/AirbnbCereal_W_Bk.otf',
	variable: '--font-lausanne-regular',
})

const cerealMedium = localFont({
	src: './fonts/AirbnbCereal_W_Md.otf',
	variable: '--font-lausanne-medium',
})

const cerealBold = localFont({
	src: './fonts/AirbnbCereal_W_Bd.otf',
	variable: '--font-lausanne-bold',
})

export const metadata: Metadata = {
	title: 'glide',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={cn(
					berkeley.variable,
					cerealLight.variable,
					cerealRegular.className,
					cerealMedium.variable,
					cerealBold.variable,
					'antialiased min-h-screen w-screen text-[12px] md:text-sm tracking-tight bg-[#f9f9f9]'
				)}
			>
				<TanstackProvider>
					<Toaster
						richColors
						icons={{
							success: <CheckCircle weight='duotone' color='green' size={16} />,
							error: <WarningCircle weight='duotone' color='crimson' size={16} />,
							info: <Info weight='duotone' color='cornflowerblue' size={16} />,
						}}
						className='font-regular tracking-normal'
					/>
					<AuthWrapper>{children}</AuthWrapper>
				</TanstackProvider>
			</body>
		</html>
	)
}
