import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const studio = localFont({
  src: '../public/assets/fonts/StudioFeixenSans.ttf',
  variable: '--font-studio',
})

const berkeley = localFont({
  src: '../public/assets/fonts/Berkeley.otf',
  variable: '--font-berkeley',
})
export const metadata: Metadata = {
  title: 'glide',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${berkeley.variable} ${studio.className} antialiased`}>{children}</body>
    </html>
  )
}
